apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels: # these labels belong to deployment
    app: cart
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: cart
      tier: app
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: cart
        tier: app
        project: roboshop
    spec:
      containers:
      - name: cart
        image: devimeena/cart:1.0.0
        envFrom:
        - configMapRef:
           name: cart
---
apiVersion: v1
kind: Service # cluster ip service bcz no need to expose to outside world
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    tier: app
    project: roboshop
  ports:
  - name: cart-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis" # redis service name
  CATALOGUE_HOST: "catalogue" # catalogue service name
  CATALOGUE_PORT: "8080"